name: CI
on:
  push:
    branches:
      - main
      - 'v*.[0-9]'
  pull_request:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          coveralls.io:443
          github.com:443
          registry.yarnpkg.com:443
          objects.githubusercontent.com:443

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20.x
    - run: yarn
    - run: yarn test --coverage
    - name: Coveralls
      uses: coverallsapp/github-action@643bc377ffa44ace6394b2b5d0d3950076de9f63 # master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
