name: CI
on:
  push:
    branches:
      - main
      - 'v*.[0-9]'
  pull_request:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          coveralls.io:443
          github.com:443
          registry.yarnpkg.com:443
          objects.githubusercontent.com:443

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: 20.x
    - run: yarn
    - run: yarn test --coverage
    - name: Coveralls
      uses: coverallsapp/github-action@0db2c3cdacfee94645baa18e49ff07a7cda3b66b # master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
