name: CI
on:
  push:
    branches:
      - main
      - 'v*.[0-9]'
  pull_request:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          coveralls.io:443
          github.com:443
          registry.yarnpkg.com:443
          objects.githubusercontent.com:443

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24.x
    - run: yarn
    - run: yarn test --coverage
    - name: Coveralls
      uses: coverallsapp/github-action@e988b39f49526ccb8bd19453bd2198bf4156bb7f # master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
